// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'ja'
	| 'pt-br'
	| 'ru'
	| 'sk'
	| 'th'
	| 'zh-cn'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	language: {
		/**
		 * E​n​g​l​i​s​h
		 */
		name: string
		/**
		 * E​n​g​l​i​s​h​ ​-​ ​I​n​t​e​r​n​a​t​i​o​n​a​l
		 */
		fullName: string
		/**
		 * E​n​g​l​i​s​h​ ​(​I​n​t​)
		 */
		descriptiveName: string
		/**
		 * e​n
		 */
		code: string
		/**
		 * �​�​�​�
		 */
		icon: string
		rtl: {
		}
	}
	site: {
		/**
		 * M​O​T​A
		 */
		description: string
		/**
		 * m​o​t​a​,​ ​s​v​e​l​t​e​k​i​t​,​ ​d​a​p​p​,​ ​b​l​o​c​k​c​h​a​i​n​,​ ​m​o​n​e​y​x​,​ ​p​a​y​p​a​s​s​,​ ​i​c​a​n​,​ ​p​a​y​t​o​,​ ​o​r​i​c​,​ ​c​o​r​e​p​a​s​s​,​ ​t​x​m​s
		 */
		keywords: string
	}
	common: {
		/**
		 * A​c​c​o​u​n​t
		 */
		account: string
		/**
		 * L​o​a​d​i​n​g​…
		 */
		loading: string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * S​u​c​c​e​s​s
		 */
		success: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * O​n​l​i​n​e
		 */
		online: string
		/**
		 * O​f​f​l​i​n​e
		 */
		offline: string
		theme: {
			/**
			 * L​i​g​h​t
			 */
			light: string
			/**
			 * D​a​r​k
			 */
			dark: string
			/**
			 * S​y​s​t​e​m
			 */
			system: string
		}
	}
	helpers: {
		coreIdValidation: {
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​C​o​r​e​ ​I​D
			 */
			error: string
			/**
			 * E​n​t​e​r​p​r​i​s​e​ ​n​e​t​w​o​r​k​ ​a​d​d​r​e​s​s​e​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​s​e​d​ ​f​o​r​ ​p​a​y​m​e​n​t​s
			 */
			enterpriseError: string
			/**
			 * C​o​r​e​ ​I​D​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			requiredError: string
		}
		wallet: {
			/**
			 * W​a​l​l​e​t​ ​i​s​ ​n​o​t​ ​c​o​n​f​i​g​u​r​e​d​.
			 */
			walletNotConfigured: string
			/**
			 * W​a​l​l​e​t​ ​i​s​ ​n​o​t​ ​i​n​s​t​a​l​l​e​d​ ​o​r​ ​e​n​a​b​l​e​d​.
			 */
			walletNotInstalled: string
			/**
			 * C​a​n​n​o​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​w​a​l​l​e​t​.
			 */
			walletCannotConnect: string
			/**
			 * W​a​l​l​e​t​ ​c​o​n​n​e​c​t​e​d​.
			 */
			walletConnected: string
			/**
			 * W​a​l​l​e​t​ ​d​i​s​c​o​n​n​e​c​t​e​d​.
			 */
			walletDisconnected: string
		}
	}
	navbar: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * S​u​p​p​o​r​t
		 */
		support: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		register: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * C​o​n​n​e​c​t
		 */
		connect: string
		/**
		 * D​i​s​c​o​n​n​e​c​t
		 */
		disconnect: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
	}
	footer: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * E​c​o​s​y​s​t​e​m
		 */
		ecosystem: string
		/**
		 * A​p​p​l​i​c​a​t​i​o​n​s
		 */
		applications: string
		/**
		 * D​e​v​e​l​o​p​e​r​s
		 */
		developers: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
		/**
		 * T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e
		 */
		termsOfService: string
		/**
		 * P​r​i​v​a​c​y​ ​P​o​l​i​c​y
		 */
		privacyPolicy: string
		/**
		 * K​e​y​ ​R​e​g​i​s​t​r​y
		 */
		keyRegistry: string
		/**
		 * ©​ ​C​o​p​y​r​i​g​h​t​ ​2​0​2​5​-​{​y​e​a​r​}​ ​M​O​T​A
		 * @param {unknown} year
		 */
		copyright: RequiredParams<'year'>
		/**
		 * P​o​w​e​r​e​d​ ​b​y​ ​M​O​T​A
		 */
		poweredBy: string
	}
	modules: {
	}
	content: {
	}
}

export type TranslationFunctions = {
	language: {
		/**
		 * English
		 */
		name: () => LocalizedString
		/**
		 * English - International
		 */
		fullName: () => LocalizedString
		/**
		 * English (Int)
		 */
		descriptiveName: () => LocalizedString
		/**
		 * en
		 */
		code: () => LocalizedString
		/**
		 * 🇺🇸
		 */
		icon: () => LocalizedString
		rtl: {
		}
	}
	site: {
		/**
		 * MOTA
		 */
		description: () => LocalizedString
		/**
		 * mota, sveltekit, dapp, blockchain, moneyx, paypass, ican, payto, oric, corepass, txms
		 */
		keywords: () => LocalizedString
	}
	common: {
		/**
		 * Account
		 */
		account: () => LocalizedString
		/**
		 * Loading…
		 */
		loading: () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Success
		 */
		success: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Menu
		 */
		menu: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Online
		 */
		online: () => LocalizedString
		/**
		 * Offline
		 */
		offline: () => LocalizedString
		theme: {
			/**
			 * Light
			 */
			light: () => LocalizedString
			/**
			 * Dark
			 */
			dark: () => LocalizedString
			/**
			 * System
			 */
			system: () => LocalizedString
		}
	}
	helpers: {
		coreIdValidation: {
			/**
			 * Please enter a valid Core ID
			 */
			error: () => LocalizedString
			/**
			 * Enterprise network addresses cannot be used for payments
			 */
			enterpriseError: () => LocalizedString
			/**
			 * Core ID is required
			 */
			requiredError: () => LocalizedString
		}
		wallet: {
			/**
			 * Wallet is not configured.
			 */
			walletNotConfigured: () => LocalizedString
			/**
			 * Wallet is not installed or enabled.
			 */
			walletNotInstalled: () => LocalizedString
			/**
			 * Cannot connect to wallet.
			 */
			walletCannotConnect: () => LocalizedString
			/**
			 * Wallet connected.
			 */
			walletConnected: () => LocalizedString
			/**
			 * Wallet disconnected.
			 */
			walletDisconnected: () => LocalizedString
		}
	}
	navbar: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Support
		 */
		support: () => LocalizedString
		/**
		 * Register
		 */
		register: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Connect
		 */
		connect: () => LocalizedString
		/**
		 * Disconnect
		 */
		disconnect: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
	}
	footer: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Ecosystem
		 */
		ecosystem: () => LocalizedString
		/**
		 * Applications
		 */
		applications: () => LocalizedString
		/**
		 * Developers
		 */
		developers: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
		/**
		 * Terms of Service
		 */
		termsOfService: () => LocalizedString
		/**
		 * Privacy Policy
		 */
		privacyPolicy: () => LocalizedString
		/**
		 * Key Registry
		 */
		keyRegistry: () => LocalizedString
		/**
		 * © Copyright 2025-{year} MOTA
		 */
		copyright: (arg: { year: unknown }) => LocalizedString
		/**
		 * Powered by MOTA
		 */
		poweredBy: () => LocalizedString
	}
	modules: {
	}
	content: {
	}
}

export type Formatters = {}
